// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hsnfklcwsgcrmpxeoqwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhzbmZrbGN3c2djcm1weGVvcXdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc5NDc0MzUsImV4cCI6MjA4MzUyMzQzNX0.eB1XAUUYJn2KpqhSP-LlzRR_zp0oRvaDR4m3FAUeWSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
